basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^register/',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login')
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
from .validators import file_size

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username

class Video(models.Model):
    caption = models.CharField(max_length=100)
    video = models.FileField(upload_to="video/%y",validators=[file_size])

    def __str__(self):
        return self.caption

class Image(models.Model):
    captionim=models.CharField(max_length=100)
    image=models.ImageField(upload_to="img/%y")

    def __str__(self):
        return self.captionim

class Documents(models.Model):
    captiondoc=models.CharField(max_length=100)
    docs=models.FileField(upload_to="doc/%y")

    def __str__(self):
        return self.captiondoc

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Video,Image,Documents

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class Video_form(forms.ModelForm):

    class Meta():
        model = Video
        fields = ('caption','video')


class ImageForm(forms.ModelForm):
    class Meta:
        model=Image
        fields=("captionim","image")

class DocumentsForm(forms.ModelForm):
    class Meta:
        model = Documents
        fields = ("captiondoc","docs")

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
from .forms import Video_form,ImageForm,DocumentsForm
from .models import Video,Image,Documents

def index(request):
    all_video=Video.objects.all()
    all_image=Image.objects.all()
    all_doc=Documents.objects.all()
    if request.method == "POST":
        form = Video_form(data=request.POST,files=request.FILES)
        formim =ImageForm(data=request.POST,files=request.FILES)
        formdoc = DocumentsForm(data=request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))
        elif formim.is_valid():
            formim.save()
            return HttpResponseRedirect(reverse('index'))
        elif formdoc.is_valid():
            formdoc.save()
            return HttpResponseRedirect(reverse('index'))

    else:
        form = Video_form()
        formim = ImageForm()
        formdoc = DocumentsForm()
    return render(request,'basic_app/index.html',{'form':form,'formim':formim,'formdoc':formdoc,'all':all_video,'obj':all_image,'alldoc':all_doc})




@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)


        if user_form.is_valid():

             user = user_form.save()
             user.set_password(user.password)
             user.save()

             registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()


    return render(request,'basic_app/registration.html',context={'user_form':user_form,'registered':registered})


def user_login(request):

    if request.method == "POST":
        username =request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            return HttpResponse("INVALID LOGIN DETAILS...")

    else:
        return render(request,'basic_app/login.html')

templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  </head>
  <body>
    <nav class = "navbar navbar-light bg-light">
      <div class="w3-bar w3-light Cornsilk">
        <ul class = 'nav navbar-nav'>
          <li><a class="w3-bar-item w3-button w3-mobile" href="{% url 'index' %}">Home</a></li>
          <li><a class="w3-bar-item w3-button w3-mobile" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="w3-bar-item w3-button w3-mobile" href="{% url 'basic_app:register' %}">Join</a></li>

        {% if user.is_authenticated %}
            <li><a class="w3-bar-item w3-button w3-mobile" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
            <li><a class="w3-bar-item w3-button w3-mobile" href="{% url 'basic_app:user_login' %}">Login</a></li>
        {% endif %}
        </ul>

      </div>

    </nav>
    <div style="background-image:url('https://images.pexels.com/photos/82256/pexels-photo-82256.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500');">
      {% block body_block %}
      {% endblock %}

    </div>


  </body>
</html>

templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}
    {% if request.user.is_authenticated %}
    <div class="w3-container">
      <h1 class="w3-center w3-animate-left">HELLO {{ request.user.username }}</h1>
      <h3 class="w3-center w3-animate-left">WELCOME TO THE DIGITAL SPACE</h3>
    </div>
    <div class="w3-container">
      <form class="w3-center w3-animate-left" action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-success btn-l type="submit">upload videos</button>
      </form>
      <p></p>
      <form class="w3-center w3-animate-left" action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{formim.as_p}}
        <button type="submit" class="btn btn-lg btn-success">Upload images</button></form>
      <p></p>
      <form class="w3-center w3-animate-left" action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{formdoc.as_p}}
        <button type="submit" class="btn btn-lg btn-success">Upload docs</button></form>
    </div>
    <hr>
    {% for x in all %}
        <h3 class="text-center mt-2 mb-2">{{x.caption}}</h3>
        <video class="embed-responsive embed-responsive-16by9" controls="controls">
            <source src="{{x.video.url}}" type="video/mp4" /></video>
    {% endfor %}

    {% for x in obj %}
      <h3 class="text-center mt-2 mb-2">{{x.captionim}}</h3>
      <img src="{{x.image.url}}" height="70%" width="70%" class="img-thumbnail" alt="...">
    {% endfor %}

    {% for x in alldoc %}
      <h3 class="text-center mt-2 mb-2">{{x.captiondoc}}</h3>
      <iframe src="{{x.docs.url}}" height="200" width="300"></iframe>
    {% endfor %}

    {% else %}
    <div class="w3-container">
      <h1 class="w3-center w3-animate-left">WELCOME TO WEBGRAM</h1>
    {% endif %}
  {% endblock %}
</div>

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron" style="background-image:url('https://images.pexels.com/photos/82256/pexels-photo-82256.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500');">
  <h1>Login</h1>
  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter the username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>

</div>


{% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="w3-container">
  {% if registered %}
     <h1>thankyou for registering!!</h1>
  {% else %}
     <h1>Register Here</h1>

     <form enctype="multipart/form-data" method="post">
       {% csrf_token %}
       {{ user_form.as_p }}
       <input type="submit" name="" value="join">

     </form>
  {% endif %}
  {% endblock %}

</div>